apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai-image-builder.yatai-common-envname" . }}
  namespace: {{ .Values.yataiSystem.namespace }}
  labels:
    {{- include "yatai-image-builder.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_ENDPOINT: {{ .Values.yatai.endpoint | quote }}
  YATAI_CLUSTER_NAME: {{ .Values.yatai.clusterName | quote }}
