# permissions for end users to edit bentoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bento-editor-role
rules:
- apiGroups:
  - resources.yatai.ai
  resources:
  - bentoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.yatai.ai
  resources:
  - bentoes/status
  verbs:
  - get
