# permissions for end users to view bentoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bento-viewer-role
rules:
- apiGroups:
  - resources.yatai.ai
  resources:
  - bentoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resources.yatai.ai
  resources:
  - bentoes/status
  verbs:
  - get
