# permissions for end users to view bentorequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bentorequest-viewer-role
rules:
- apiGroups:
  - resources.yatai.ai
  resources:
  - bentorequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resources.yatai.ai
  resources:
  - bentorequests/status
  verbs:
  - get
